---
- name: Ensure tmux is installed.
  tags: apt, dnf
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

- name: Install tmux-powerline.
  tags: dnf
  ansible.builtin.dnf:
    name: tmux-powerline
    state: present
  become: true
  when: ('powerline' in packages_common) and (ansible_os_family == 'RedHat')

- name: Copy tmux configuration file ~/.tmux.conf.
  ansible.builtin.template:
    src: tmux.conf.j2
    dest: "{{ homepath }}/.tmux.conf"
    mode: '0644'
  when: ('powerline' in packages_common)