---
- name: Ensure vim is installed (apt).
  tags: apt
  ansible.builtin.apt:
    name: vim-nox
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure vim is installed (dnf).
  tags: dnf
  ansible.builtin.dnf:
    name: vim-enhanced
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Set vim as default editor.
  ansible.builtin.copy:
    dest: "{{ homepath }}/.bashrc.d/editor"
    content: |
      export EDITOR=/usr/bin/vim
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Install vim-powerline.
  tags: dnf
  ansible.builtin.dnf:
    name: tmux-powerline
    state: present
  become: true
  when: ('powerline' in packages_common) and (ansible_os_family == 'RedHat')

- name: Copy vim configuration file ~/.vimrc.
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ homepath }}/.vimrc"
    mode: '0644'
  when: ('powerline' in packages_common)